---
language: python

install:
  - pip install molecule docker

script:
  - molecule lint
  - molecule destroy
  - molecule dependency
  - molecule syntax
  - molecule converge
  - travis_wait 20 molecule idempotence
  - molecule side-effect
  - molecule verify
  - molecule destroy
