---
    # Grafana installation
    grafana_local_repo: /opt/localrepo/grafana
    grafana_yum_repo_template: repos/grafana.repo.j2
    # Grafana auth
    grafana_security:
      admin_user: "{{ grafana_admin_name }}"
      admin_password: "{{ grafana_admin_passwd }}"
    # Grafana datasource configuration
    grafana_datasources:
    - name: InfluxDB
      type: influxdb
      isDefault: true
      access: proxy
      url: 'http://127.0.0.1:8086'
      database: "{{ influxdb_metrics_db }}"
      user: "{{ influxdb_metrics_ro_name }}"
      password: "{{ influxdb_metrics_ro_passwd }}"
    # Grafana LDAP configuration
    grafana_auth:
      ldap:
        enabled: true
        config_file: "/etc/grafana/ldap.toml"
        allow_sign_up: true
    grafana_ldap:
      verbose_logging: true
      servers:
        host: 192.168.1.1
        port: 389
        use_ssl: false
        start_tls: false
        ssl_skip_verify: true
        bind_dn: "CORP\\%s"
        search_filter: "(sAMAccountName=%s)"
        search_base_dns:
          - "dc=corp,dc=local"
        attributes:
          name: givenName
          surname: sn
          username: sAMAccountName
          member_of: memberOf
          email: mail
      group_mappings:
        - name: Main Org.
          id: 1
          groups:
            - group_dn: "*"
              org_role: Viewer
        # Grafana Organization should be created manualy
        - name: Demo project
          id: 2
          # C:\Users\Administrator>dsquery group -name demo_admins
          # "CN=demo_admins,CN=Users,DC=CORP,DC=local"
          groups:
            - group_dn: "cn=demo_admins,cn=Users,dc=CORP,dc=local"
              org_role: Admin
            - group_dn: "cn=demo_editors,cn=Users,dc=CORP,dc=local"
              org_role: Editor
    # Grafana backup configuration
    grafana_scripts_user: root
    grafana_scripts_folder: /root/.scripts
    # Grafana API key should be created manualy
    grafana_api_key: "{{ grafana_backup_api }}"
