---
- name: Configure Grafana server
  hosts: grafana
  become: true
  vars:
    grafana_local_repo: /opt/localrepo/grafana
    grafana_yum_repo_template: repos/grafana.repo.j2
    grafana_security:
      admin_user: admin
      admin_password: admin
    grafana_datasources:
      - name: InfluxDB
        type: influxdb
        url: http://localhost:8086
        access: proxy
        database: metrics
    grafana_auth:
      ldap:
        enabled: true
        config_file: "/etc/grafana/ldap.toml"
        allow_sign_up: true
    grafana_ldap:
      verbose_logging: true
      servers:
        host: 192.168.1.1
        port: 389
        use_ssl: false
        start_tls: false
        ssl_skip_verify: true
        bind_dn: "CORP\\%s"
        search_filter: "(sAMAccountName=%s)"
        search_base_dns:
          - "dc=corp,dc=local"
        attributes:
          name: givenName
          surname: sn
          username: sAMAccountName
          member_of: memberOf
          email: mail
      group_mappings:
        - name: Main Org.
          id: 1
          groups:
            - group_dn: "*"
              org_role: Viewer
        # Organization should be created manualy
        - name: Demo project
          id: 2
          groups:
            - group_dn: "cn=demo_admins,cn=Users,dc=CORP,dc=local"
              org_role: Admin
            - group_dn: "cn=demo_editors,cn=Users,dc=CORP,dc=local"
              org_role: Editor
    grafana_scripts_user: root
    grafana_scripts_folder: /root/.scripts
    grafana_api_key: eyJrIjoieXZiRVc0YW02SnhFdm9qbUhqTTlCMWVmWUhpUHNXOEUiLCJuIjoiYmFja3VwIiwiaWQiOjF9
  roles:
    - grafana_repo
    - cloudalchemy.grafana
    - grafana_backup
