---
- name: Configure InfluxDB server
  hosts: influxdb
  roles:
    - influxdb_repo
    - hostberg.influxdb
    - influxdb_backup
  environment:
    INFLUX_USERNAME: "{{ influxdb_admin_name }}"
    INFLUX_PASSWORD: "{{ influxdb_admin_passwd }}"
